# Generated by Django 5.1.1 on 2024-09-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo_task',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
