# Generated by Django 5.1.1 on 2024-09-06 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_todo_task_due_date_todo_task_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='Todo_Task',
        ),
        migrations.AddField(
            model_name='todo_task',
            name='suggestions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='todo_task',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='todo_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_list', to='main_app.todo_task'),
        ),
    ]
