# Generated by Django 5.1.1 on 2024-09-06 20:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_suggestion_todo_task_todo_task_suggestions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteToProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=200, unique=True)),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2024, 9, 13, 20, 17, 50, 283232, tzinfo=datetime.timezone.utc))),
                ('is_accepted', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.project')),
            ],
        ),
    ]
