# Generated by Django 5.1.1 on 2024-09-06 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_invitetoproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitetoproject',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 13, 20, 18, 14, 841010, tzinfo=datetime.timezone.utc)),
        ),
    ]
