# Generated by Django 5.1.1 on 2024-09-10 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_invitetoproject_expire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo_task',
            old_name='description',
            new_name='notes',
        ),
        migrations.AlterField(
            model_name='invitetoproject',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 17, 22, 15, 28, 914360, tzinfo=datetime.timezone.utc)),
        ),
    ]
