# Generated by Django 5.1.1 on 2024-09-10 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_description_todo_task_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitetoproject',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 17, 22, 20, 42, 595804, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='todo_task',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
